// 原版技能数据（PristonTale 原版 20 技能/职业，含 10 职业 = 200 技能）。
// 数据来源：wartale.com 全部 50 个技能页逐页抓取（docs/wartale-skills.tsv），
// 每技能含官方英文名（name）、需求等级（reqLv）、分类（type），200 项全量覆盖。
// 图标 URL 与资源资产 image/sinimage/skill/{职业}/button/*.bmp 一一对应（iconFile）。
// alt = 早期 GLM/资源文件名引申的旧英译名（与 wartale 官方名不一致时保留参照）。
// 与 DB 的 skillinfo 无关（那是 EU 私服删减的 16 技能版）。
// 顺序 = 图标文件编号序，每 4 个一页（T1/T2/T3/T4/T5 共 5 页），index 0-3 页内技能。

export interface SkillDef {
  iconFile: string; // button/ 目录下的 bmp 文件名（原文件小写含空格）
  name: string;     // wartale 官方技能名
  reqLv: number;    // 需求等级
  type: string;     // 分类（Buff/Passive/Single Target/Target Area/Target Area(heal)/Summon/Active...）
  alt?: string;     // 旧译名（仅与 wartale 官方名不一致时存在）
}

// 职业 id（服务端 job）→ 资源目录名
export const CLASS_DIR: Record<number, string> = {
  1: 'fighter', 2: 'mecha', 3: 'archer', 4: 'pikeman', 5: 'atalanta',
  6: 'knight', 7: 'magician', 8: 'priestess', 9: 'assassin', 10: 'shaman',
};

export const SKILLS: Record<string, SkillDef[]> = {
  fighter: [
    { iconFile: 'tf10 m_mastery.bmp', name: 'Melee Mastery', reqLv: 10, type: 'Passive' },
    { iconFile: 'tf12 f_attribute.bmp', name: 'Fire Attribute', reqLv: 12, type: 'Passive' },
    { iconFile: 'tf14 raving.bmp', name: 'Raving', reqLv: 14, type: 'Single Target' },
    { iconFile: 'tf17 impact.bmp', name: 'Impact', reqLv: 17, type: 'Single Target' },
    { iconFile: 'tf20 t_impact.bmp', name: 'Triple Impact', reqLv: 20, type: 'Single Target' },
    { iconFile: 'tf23 b_swing.bmp', name: 'Brutal Swing', reqLv: 23, type: 'Single Target' },
    { iconFile: 'tf26 roar.bmp', name: 'Roar', reqLv: 26, type: 'Active', alt: 'War Cry' },
    { iconFile: 'tf30 r_zecram.bmp', name: 'Rage of Zecram', reqLv: 30, type: 'Target Area' },
    { iconFile: 'tf40 concentration.bmp', name: 'Concentration', reqLv: 40, type: 'Buff' },
    { iconFile: 'tf43 a_crash.bmp', name: 'Avenging Crash', reqLv: 43, type: 'Single Target' },
    { iconFile: 'tf46 s_axe.bmp', name: 'Swiftness', reqLv: 46, type: 'Buff', alt: 'Swift Axe' },
    { iconFile: 'tf50 b_crash.bmp', name: 'Bone Crash', reqLv: 50, type: 'Single Target' },
    { iconFile: 'tf60 destoryer.bmp', name: 'Destroyer', reqLv: 60, type: 'Single Target' },
    { iconFile: 'tf63 berserker.bmp', name: 'Berserker', reqLv: 63, type: 'Buff' },
    { iconFile: 'tf66 c_strike.bmp', name: 'Cyclone Strike', reqLv: 66, type: 'Target Area' },
    { iconFile: 'tf70 b_health.bmp', name: 'Boost Health', reqLv: 70, type: 'Passive' },
    { iconFile: 'tf100 survival_instinct.bmp', name: 'Charge', reqLv: 80, type: 'Single Target', alt: 'Survival Instinct' },
    { iconFile: 'tf103 sesmic_impact.bmp', name: 'Inner Soul', reqLv: 83, type: 'Buff', alt: 'Seismic Impact' },
    { iconFile: 'tf106 ruthless_zecram.bmp', name: 'Hellion', reqLv: 86, type: 'Summon', alt: 'Ruthless Zecram' },
    { iconFile: 'tf110 whirlwind.bmp', name: 'Flame Vortex', reqLv: 90, type: 'Area Attack', alt: 'Whirlwind' },
  ],
  mecha: [
    { iconFile: 'tm10 ex_shield.bmp', name: 'Extreme Shield', reqLv: 10, type: 'Buff' },
    { iconFile: 'tm12 m_bomb.bmp', name: 'Mechanic Bomb', reqLv: 12, type: 'Target Area' },
    { iconFile: 'tm14 p_attribute.bmp', name: 'Reverse Engineering', reqLv: 14, type: 'Passive', alt: 'Poison Attribute' },
    { iconFile: 'tm17 ph_absorb.bmp', name: 'Physical Absorption', reqLv: 17, type: 'Buff', alt: 'Physical Absorb' },
    { iconFile: 'tm20 g_smash.bmp', name: 'Great Smash', reqLv: 20, type: 'Single Target' },
    { iconFile: 'tm23 maximize.bmp', name: 'Maximize', reqLv: 23, type: 'Buff' },
    { iconFile: 'tm26 automation.bmp', name: 'Automation', reqLv: 26, type: 'Buff' },
    { iconFile: 'tm30 spark.bmp', name: 'Spark', reqLv: 30, type: 'Target Area' },
    { iconFile: 'tm40 m_armor.bmp', name: 'Metal Armor', reqLv: 40, type: 'Buff' },
    { iconFile: 'tm43 grand_smash.bmp', name: 'Grand Smash', reqLv: 43, type: 'Single Target' },
    { iconFile: 'tm44 m_weapon.bmp', name: 'Mechanic Weapon Mastery', reqLv: 46, type: 'Passive', alt: 'Mechanic Weapon' },
    { iconFile: 'tm50 s_shield.bmp', name: 'Spark Shield', reqLv: 50, type: 'Buff' },
    { iconFile: 'tm60 impulsion.bmp', name: 'Impulsion', reqLv: 60, type: 'Target Area' },
    { iconFile: 'tm63 compulsion.bmp', name: 'Compulsion', reqLv: 63, type: 'Buff' },
    { iconFile: 'tm66 m_sphere.bmp', name: 'Magnetic Sphere', reqLv: 66, type: 'Active' },
    { iconFile: 'tm70 m_golem.bmp', name: 'Metal Golem', reqLv: 70, type: 'Summon' },
    { iconFile: 'tm100 rupture.bmp', name: 'Precision', reqLv: 80, type: 'Buff', alt: 'Rupture' },
    { iconFile: 'tm103 parasit_shot.bmp', name: 'Trine Shield', reqLv: 83, type: 'Buff', alt: 'Parasit Shot' },
    { iconFile: 'tm106 hardening_shield.bmp', name: 'Gravitation', reqLv: 86, type: 'Buff', alt: 'Hardening Shield' },
    { iconFile: 'tm110 magnetic_discharge.bmp', name: 'Obliterate', reqLv: 90, type: 'Single Target', alt: 'Magnetic Discharge' },
  ],
  archer: [
    { iconFile: 'ta10 s_hawk.bmp', name: 'Scout Hawk', reqLv: 10, type: 'Buff' },
    { iconFile: 'ta12 s_mastery.bmp', name: 'Shooting Mastery', reqLv: 12, type: 'Passive' },
    { iconFile: 'ta14 w_arrow.bmp', name: 'Wind Arrow', reqLv: 14, type: 'Single Target' },
    { iconFile: 'ta17 p_aim.bmp', name: 'Perfect Aim', reqLv: 17, type: 'Single Target' },
    { iconFile: 'ta20 d_eye.bmp', name: 'Dion\'s Eye', reqLv: 20, type: 'Passive', alt: 'Dions Eye' },
    { iconFile: 'ta23 falcon.bmp', name: 'Falcon', reqLv: 23, type: 'Buff' },
    { iconFile: 'ta26 a_rage.bmp', name: 'Arrow of Rage', reqLv: 26, type: 'Target Area' },
    { iconFile: 'ta30 avalanchie.bmp', name: 'Avalanche', reqLv: 30, type: 'Single Target' },
    { iconFile: 'ta40 e_shot.bmp', name: 'Elemental Shot', reqLv: 40, type: 'Target Area' },
    { iconFile: 'ta43 g_falcon.bmp', name: 'Golden Falcon', reqLv: 43, type: 'Buff' },
    { iconFile: 'ta46 b_shot.bmp', name: 'Bomb Shot', reqLv: 46, type: 'Target Area' },
    { iconFile: 'ta50 perforation.bmp', name: 'Perforation', reqLv: 50, type: 'Target Area' },
    { iconFile: 'ta60 r_wolverin.bmp', name: 'Wolverine', reqLv: 60, type: 'Summon', alt: 'Recall Wolverin' },
    { iconFile: 'ta63 e_mastery.bmp', name: 'Evasion Mastery', reqLv: 63, type: 'Passive' },
    { iconFile: 'ta66 p_shot.bmp', name: 'Phoenix Shot', reqLv: 66, type: 'Single Target' },
    { iconFile: 'ta70 f_o_nature.bmp', name: 'Force of Nature', reqLv: 70, type: 'Buff' },
    { iconFile: 'ta100 lethal_sight.bmp', name: 'Stun Arrow', reqLv: 80, type: 'Active', alt: 'Lethal Sight' },
    { iconFile: 'ta103 fierce_wind.bmp', name: 'Phoenix Speed', reqLv: 83, type: 'Buff', alt: 'Fierce Wind' },
    { iconFile: 'ta106 entailing_roots.bmp', name: 'Leap Shot', reqLv: 86, type: 'Single Target', alt: 'Entailing Roots' },
    { iconFile: 'ta110 bombardment.bmp', name: 'Solar Arrow', reqLv: 90, type: 'Target Area', alt: 'Bombardment' },
  ],
  pikeman: [
    { iconFile: 'tp10 p_wind.bmp', name: 'Pike Wind', reqLv: 10, type: 'Area Attack' },
    { iconFile: 'tp12 i_attribute.bmp', name: 'Ice Attribute', reqLv: 12, type: 'Passive' },
    { iconFile: 'tp14 cri_hit.bmp', name: 'Critical Hit', reqLv: 14, type: 'Single Target' },
    { iconFile: 'tp17 j_crash.bmp', name: 'Jumping Crash', reqLv: 17, type: 'Single Target' },
    { iconFile: 'tp20 g_pike.bmp', name: 'Ground Pike', reqLv: 20, type: 'Area Attack' },
    { iconFile: 'tp23 tornado.bmp', name: 'Tornado', reqLv: 23, type: 'Target Area' },
    { iconFile: 'tp26 w_d_mastery.bmp', name: 'Weapon Defense Mastery', reqLv: 26, type: 'Passive', alt: 'Weapon Defence Mastery' },
    { iconFile: 'tp30 expasion.bmp', name: 'Expansion', reqLv: 30, type: 'Target Area' },
    { iconFile: 'tp40 v_spear.bmp', name: 'Venom Spear', reqLv: 40, type: 'Area Attack' },
    { iconFile: 'tp43 vanish.bmp', name: 'Vanish', reqLv: 43, type: 'Buff' },
    { iconFile: 'tp46 c_mastery.bmp', name: 'Critical Mastery', reqLv: 46, type: 'Passive' },
    { iconFile: 'tp50 c_lance.bmp', name: 'Chain Lancer', reqLv: 50, type: 'Single Target', alt: 'Chain Lance' },
    { iconFile: 'tp60 a_eye.bmp', name: 'Assassin\'s Eye', reqLv: 60, type: 'Active', alt: 'Assassin Eye' },
    { iconFile: 'tp63 c_strike.bmp', name: 'Charging Strike', reqLv: 63, type: 'Single Target' },
    { iconFile: 'tp66 vague.bmp', name: 'Vague', reqLv: 66, type: 'Buff' },
    { iconFile: 'tp70 s_master.bmp', name: 'Shadow Master', reqLv: 70, type: 'Single Target' },
    { iconFile: 'tp100 ring_spears.bmp', name: 'Attack Rating Mastery', reqLv: 80, type: 'Passive', alt: 'Ring Spears' },
    { iconFile: 'tp103 focus.bmp', name: 'Lethal Strike', reqLv: 83, type: 'Single Target', alt: 'Focus' },
    { iconFile: 'tp106 death_master.bmp', name: 'Dodge', reqLv: 86, type: 'Active', alt: 'Death Master' },
    { iconFile: 'tp110 twister.bmp', name: 'Vorpal Dive', reqLv: 90, type: 'Area Attack', alt: 'Twister' },
  ],
  atalanta: [
    { iconFile: 'ma10 s_strike.bmp', name: 'Shield Strike', reqLv: 10, type: 'Target Area' },
    { iconFile: 'ma12 farina.bmp', name: 'Farina', reqLv: 12, type: 'Single Target' },
    { iconFile: 'ma14 t_mastery.bmp', name: 'Throwing Mastery', reqLv: 14, type: 'Passive' },
    { iconFile: 'ma17 v_spear.bmp', name: 'Vigor Spear', reqLv: 17, type: 'Single Target' },
    { iconFile: 'ma20 windy.bmp', name: 'Windy', reqLv: 20, type: 'Buff' },
    { iconFile: 'ma23 t_javelin.bmp', name: 'Twist Javelin', reqLv: 23, type: 'Single Target' },
    { iconFile: 'ma26 s_sucker.bmp', name: 'Soul Sucker', reqLv: 26, type: 'Single Target' },
    { iconFile: 'ma30 f_javelin.bmp', name: 'Fire Javelin', reqLv: 30, type: 'Single Target' },
    { iconFile: 'ma40 split_javelin.bmp', name: 'Split Javelin', reqLv: 40, type: 'Single Target' },
    { iconFile: 'ma43 t_of_valhalla.bmp', name: 'Triumph of Valhalla', reqLv: 43, type: 'Buff' },
    { iconFile: 'ma46 l_javelin.bmp', name: 'Lightning Javelin', reqLv: 46, type: 'Target Area' },
    { iconFile: 'ma50 storm_javelin.bmp', name: 'Storm Javelin', reqLv: 50, type: 'Target Area' },
    { iconFile: 'ma60 h_o_valhalla.bmp', name: 'Hall of Valhalla', reqLv: 60, type: 'Buff' },
    { iconFile: 'ma63 x_rage.bmp', name: 'Extreme Rage', reqLv: 63, type: 'Target Area', alt: 'X Rage' },
    { iconFile: 'ma66 f_javelin.bmp', name: 'Frost Javelin', reqLv: 66, type: 'Buff' },
    { iconFile: 'ma70 vengeance.bmp', name: 'Vengeance', reqLv: 70, type: 'Single Target' },
    { iconFile: 'ma100 s_tiger.bmp', name: 'Chimera of Light', reqLv: 80, type: 'Summon', alt: 'S Tiger' },
    { iconFile: 'ma103 golden_apple.bmp', name: 'Poison Javelin', reqLv: 83, type: 'Target Area', alt: 'Golden Apple' },
    { iconFile: 'ma106 plague_javelin.bmp', name: 'Amazon Rage', reqLv: 86, type: 'Buff', alt: 'Plague Javelin' },
    { iconFile: 'ma110 combo_javelin.bmp', name: 'Javelin Mastery', reqLv: 90, type: 'Passive', alt: 'Combo Javelin' },
  ],
  knight: [
    { iconFile: 'mn10 s_blast.bmp', name: 'Sword Blast', reqLv: 10, type: 'Target Area' },
    { iconFile: 'mn12 h_body.bmp', name: 'Holy Body', reqLv: 12, type: 'Passive' },
    { iconFile: 'mn14 p_traning.bmp', name: 'Physical Training', reqLv: 14, type: 'Passive' },
    { iconFile: 'mn17 d_crash.bmp', name: 'Double Crash', reqLv: 17, type: 'Single Target' },
    { iconFile: 'mn20 h_valor.bmp', name: 'Holy Valor', reqLv: 20, type: 'Buff' },
    { iconFile: 'mn23 brandish.bmp', name: 'Brandish', reqLv: 23, type: 'Target Area' },
    { iconFile: 'mn26 piercing.bmp', name: 'Piercing', reqLv: 26, type: 'Target Area' },
    { iconFile: 'mn30 d_spirit.bmp', name: 'Drastic Spirit', reqLv: 30, type: 'Buff' },
    { iconFile: 'mn40 s_mastery.bmp', name: 'Sword Mastery', reqLv: 40, type: 'Passive' },
    { iconFile: 'mn43 d_inhalation.bmp', name: 'Divine Shield', reqLv: 43, type: 'Buff', alt: 'Divine Inhalation' },
    { iconFile: 'mn46 h_incantation.bmp', name: 'Holy Incantation', reqLv: 46, type: 'Active' },
    { iconFile: 'mn50 g_cross.bmp', name: 'Grand Cross', reqLv: 50, type: 'Single Target' },
    { iconFile: 'mn60 s_o_justice.bmp', name: 'Sword of Justice', reqLv: 60, type: 'Target Area' },
    { iconFile: 'mn63 g_shield.bmp', name: 'Godly Shield', reqLv: 63, type: 'Buff' },
    { iconFile: 'mn66 g_bless.bmp', name: 'God\'s Blessing', reqLv: 66, type: 'Buff', alt: 'God Bless' },
    { iconFile: 'mn70 d_piercing.bmp', name: 'Divine Piercing', reqLv: 70, type: 'Single Target' },
    { iconFile: 'mn100 holy_conviction.bmp', name: 'Lightning Sword', reqLv: 80, type: 'Area Attack', alt: 'Holy Conviction' },
    { iconFile: 'mn103 divine_inquisiton.bmp', name: 'Undead Bane', reqLv: 83, type: 'Passive', alt: 'Divine Inquisition' },
    { iconFile: 'mn106 glorious_shield.bmp', name: 'Zealous Reach', reqLv: 86, type: 'Active', alt: 'Glorious Shield' },
    { iconFile: 'mn110 divine_cross.bmp', name: 'Holy Aura', reqLv: 90, type: 'Buff', alt: 'Divine Cross' },
  ],
  magician: [
    { iconFile: 'mm10 agony.bmp', name: 'Agony', reqLv: 10, type: 'Active' },
    { iconFile: 'mm12 firebolt.bmp', name: 'Fire Bolt', reqLv: 12, type: 'Single Target' },
    { iconFile: 'mm14 zenith.bmp', name: 'Zenith', reqLv: 14, type: 'Buff' },
    { iconFile: 'mm17 fireball.bmp', name: 'Fire Ball', reqLv: 17, type: 'Target Area' },
    { iconFile: 'mm20 m_mastery.bmp', name: 'Mental Mastery', reqLv: 20, type: 'Passive' },
    { iconFile: 'mm23 watornado.bmp', name: 'Watornado', reqLv: 23, type: 'Target Area' },
    { iconFile: 'mm26 e_weapon.bmp', name: 'Enchant Weapon', reqLv: 26, type: 'Buff' },
    { iconFile: 'mm30 d_ray.bmp', name: 'Death Ray', reqLv: 30, type: 'Single Target', alt: 'Dead Ray' },
    { iconFile: 'mm40 e_shield.bmp', name: 'Energy Shield', reqLv: 40, type: 'Buff' },
    { iconFile: 'mm43 diastrophism.bmp', name: 'Diastrophism', reqLv: 43, type: 'Area Attack' },
    { iconFile: 'mm46 s_elemental.bmp', name: 'Spirit Elemental', reqLv: 46, type: 'Buff' },
    { iconFile: 'mm50 d_sword.bmp', name: 'Dancing Sword', reqLv: 50, type: 'Buff' },
    { iconFile: 'mm60 f_elemental.bmp', name: 'Fire Elemental', reqLv: 60, type: 'Summon' },
    { iconFile: 'mm63 f_wave.bmp', name: 'Flame Wave', reqLv: 63, type: 'Target Area' },
    { iconFile: 'mm66 distortion.bmp', name: 'Distortion', reqLv: 66, type: 'Active' },
    { iconFile: 'mm70 meteo.bmp', name: 'Meteorite', reqLv: 70, type: 'Target Area', alt: 'Meteo' },
    { iconFile: 'mm100 wizardtrance.bmp', name: 'Magic Source', reqLv: 80, type: 'Buff', alt: 'Wizard Trance' },
    { iconFile: 'mm103 stone_skin.bmp', name: 'Amplify', reqLv: 83, type: 'Passive', alt: 'Stone Skin' },
    { iconFile: 'mm106 redray.bmp', name: 'Stone Spike', reqLv: 86, type: 'Area Attack', alt: 'Red Ray' },
    { iconFile: 'mm110 cataclysm.bmp', name: 'Dance of Calamity', reqLv: 90, type: 'Single Target', alt: 'Cataclysm' },
  ],
  priestess: [
    { iconFile: 'mp10 healing.bmp', name: 'Healing', reqLv: 10, type: 'Active' },
    { iconFile: 'mp12 holybolt.bmp', name: 'Holy Bolt', reqLv: 12, type: 'Single Target' },
    { iconFile: 'mp14 m_spark.bmp', name: 'Multi Spark', reqLv: 14, type: 'Single Target' },
    { iconFile: 'mp17 holymind.bmp', name: 'Holy Mind', reqLv: 17, type: 'Active' },
    { iconFile: 'mp20 meditation.bmp', name: 'Meditation', reqLv: 20, type: 'Passive' },
    { iconFile: 'mp23 d_lightning.bmp', name: 'Divine Lightning', reqLv: 23, type: 'Area Attack' },
    { iconFile: 'mp26 h_reflection.bmp', name: 'Holy Reflection', reqLv: 26, type: 'Buff' },
    { iconFile: 'mp30 g_healing.bmp', name: 'Grand Healing', reqLv: 30, type: 'Active' },
    { iconFile: 'mp40 v_ball.bmp', name: 'Vigor Ball', reqLv: 40, type: 'Single Target' },
    { iconFile: 'mp43 resurrection.bmp', name: 'Resurrection', reqLv: 43, type: 'Active' },
    { iconFile: 'mp46 extinction.bmp', name: 'Extinction', reqLv: 46, type: 'Active' },
    { iconFile: 'mp50 v_life.bmp', name: 'Virtual Life', reqLv: 50, type: 'Buff' },
    { iconFile: 'mp60 g_spike.bmp', name: 'Glacial Spike', reqLv: 60, type: 'Target Area' },
    { iconFile: 'mp63 r_field.bmp', name: 'Regeneration Field', reqLv: 63, type: 'Active' },
    { iconFile: 'mp66 c_lightning.bmp', name: 'Chain Lightning', reqLv: 66, type: 'Target Area' },
    { iconFile: 'mp70 s_muspell.bmp', name: 'Summon Muspell', reqLv: 70, type: 'Buff' },
    { iconFile: 'mp100 ice_elemental.bmp', name: 'Divine Force', reqLv: 80, type: 'Buff', alt: 'Ice Elemental' },
    { iconFile: 'mp103 lightning_surge.bmp', name: 'Ice Meteorite', reqLv: 83, type: 'Area Attack', alt: 'Lightning Surge' },
    { iconFile: 'mp106 heavenly_light.bmp', name: 'Thunderstorm', reqLv: 86, type: 'Area Attack', alt: 'Heavenly Light' },
    { iconFile: 'mp110 consecration.bmp', name: 'Divine Cleansing', reqLv: 90, type: 'Active', alt: 'Consecration' },
  ],
  assassin: [
    { iconFile: 'ta10 stingger.bmp', name: 'Stinger', reqLv: 10, type: 'Single Target', alt: 'Stingger' },
    { iconFile: 'ta12 r_hit.bmp', name: 'Double Blow', reqLv: 12, type: 'Single Target', alt: 'Running Hit' },
    { iconFile: 'ta14 d_mastery.bmp', name: 'Dual Wield Mastery', reqLv: 14, type: 'Passive', alt: 'Dual Sword Mastery' },
    { iconFile: 'ta17 wisp.bmp', name: 'Wisp', reqLv: 17, type: 'Active' },
    { iconFile: 'ta20 v_throne.bmp', name: 'Venom Thorn', reqLv: 20, type: 'Single Target', alt: 'Venom Throne' },
    { iconFile: 'ta23 alas.bmp', name: 'Alas', reqLv: 23, type: 'Buff' },
    { iconFile: 'ta26 s_shock.bmp', name: 'Soul Shock', reqLv: 26, type: 'Active' },
    { iconFile: 'ta30 a_mastery.bmp', name: 'Blade Mastery', reqLv: 30, type: 'Passive', alt: 'Attack Mastery' },
    { iconFile: 'ta40 s_sword.bmp', name: 'Finishing Blow', reqLv: 40, type: 'Single Target', alt: 'Sore Sword' },
    { iconFile: 'ta43 b_up.bmp', name: 'Gust Slash', reqLv: 43, type: 'Target Area', alt: 'Beat Up' },
    { iconFile: 'ta46 inpes.bmp', name: 'Inpes', reqLv: 46, type: 'Buff' },
    { iconFile: 'ta50 blind.bmp', name: 'Deception', reqLv: 50, type: 'Buff', alt: 'Blind' },
    { iconFile: 'ta60 f_wind.bmp', name: 'Frost Wind', reqLv: 60, type: 'Single Target' },
    { iconFile: 'ta63 f_mastery.bmp', name: 'Fatal Mastery', reqLv: 63, type: 'Passive', alt: 'Critical Mastery' },
    { iconFile: 'ta66 polluted.bmp', name: 'Pollute', reqLv: 66, type: 'Area Attack', alt: 'Polluted' },
    { iconFile: 'ta70 p_shadow.bmp', name: 'Ninja Shadow', reqLv: 70, type: 'Single Target', alt: 'Pasting Shadow' },
    { iconFile: 'ts80 j_bomb.bmp', name: 'Shadow Bomb', reqLv: 80, type: 'Area Attack' },
    { iconFile: 'ts83 r_slash.bmp', name: 'Rising Slash', reqLv: 83, type: 'Target Area' },
    { iconFile: 'ts86 v_stab.bmp', name: 'Violent Stab', reqLv: 86, type: 'Single Target', alt: 'Violence Stab' },
    { iconFile: 'ts90 storm.bmp', name: 'Shadow Storm', reqLv: 90, type: 'Target Area', alt: 'Storm' },
  ],
  shaman: [
    { iconFile: 'ms10 darkbolt.bmp', name: 'Dark Bolt', reqLv: 10, type: 'Single Target' },
    { iconFile: 'ms12 darkwave.bmp', name: 'Dark Wave', reqLv: 12, type: 'Single Target' },
    { iconFile: 'ms14 curselazy.bmp', name: 'Inertia', reqLv: 14, type: 'Active', alt: 'Curse Lazy' },
    { iconFile: 'ms17 i_peace.bmp', name: 'Inner Peace', reqLv: 17, type: 'Passive' },
    { iconFile: 'ms20 s_flare.bmp', name: 'Spiritual Flare', reqLv: 20, type: 'Target Area' },
    { iconFile: 'ms23 s_manacle.bmp', name: 'Spiritual Manacle', reqLv: 23, type: 'Active', alt: 'Soul Manacle' },
    { iconFile: 'ms26 c_hunt.bmp', name: 'Chasing Hunt', reqLv: 26, type: 'Active' },
    { iconFile: 'ms30 a_migal.bmp', name: 'Advent Migal', reqLv: 30, type: 'Buff' },
    { iconFile: 'ms40 r_maker.bmp', name: 'Rainmaker', reqLv: 40, type: 'Buff', alt: 'Rain Maker' },
    { iconFile: 'ms43 l_ghost.bmp', name: 'Phantom Call', reqLv: 43, type: 'Area Attack', alt: 'Land of Ghost' },
    { iconFile: 'ms46 haunt.bmp', name: 'Haunt', reqLv: 46, type: 'Single Target' },
    { iconFile: 'ms50 scratch.bmp', name: 'Scratch', reqLv: 50, type: 'Single Target' },
    { iconFile: 'ms60 r_knight.bmp', name: 'Crimson Knight', reqLv: 60, type: 'Summon', alt: 'Recall Bloody Knight' },
    { iconFile: 'ms63 judge.bmp', name: 'Judgement', reqLv: 63, type: 'Single Target' },
    { iconFile: 'ms66 a_midranda.bmp', name: 'Advent Midranda', reqLv: 66, type: 'Buff' },
    { iconFile: 'ms70 m_pray.bmp', name: 'Mourning Pray', reqLv: 70, type: 'Area Attack', alt: 'Mourning of Pray' },
    { iconFile: 'ms80 creed.bmp', name: 'Creed', reqLv: 80, type: 'Buff' },
    { iconFile: 'ms83 p_deity.bmp', name: 'Press Deity', reqLv: 83, type: 'Target Area', alt: 'Press of Deity' },
    { iconFile: 'ms86 g_nail.bmp', name: 'Phantom Nail', reqLv: 86, type: 'Target Area', alt: 'Ghosty Nail' },
    { iconFile: 'ms90 h_regene.bmp', name: 'Occult Life', reqLv: 90, type: 'Passive', alt: 'High Regeneration' },
  ],
};

export const SKILLS_PER_PAGE = 4;
export const SKILL_PAGES = 5;

// 各职业技能树 5 阶（T1-T5）进阶职业名（wartale 页序，原版转职体系）。
// T5 为最终职业；未来新增 T6 时在数组末尾追加。
export const CLASS_TIERS: Record<string, string[]> = {
  fighter: ['Fighter', 'Warrior', 'Champion', 'Immortal Warrior', 'Warlord'],
  mecha: ['Mechanician', 'Mechanic Master', 'Metal Leader', 'Heavy Metal', 'Titanium Chief'],
  archer: ['Archer', 'Huntress Master', "Dion's Disciple", 'Sagittarius', 'Phoenix Master'],
  pikeman: ['Pikeman', 'Combatant', 'Lancer', 'Lancelot', 'Phalanx'],
  atalanta: ['Atalanta', 'Valkyrie', 'Brynhild', 'Valhalla', 'Sentinel'],
  knight: ['Knight', 'Paladin', 'Holy Knight', 'Saint Knight', 'Crusader'],
  magician: ['Magician', 'Wizard', 'Royal Wizard', 'Arch Mage', 'Elemental Master'],
  priestess: ['Priestess', 'Saintess', 'Bishop', 'Celestial', 'Prophetess'],
  assassin: ['Assassin', 'Rogue', 'Hermit', 'Shadower', 'Nightwalker'],
  shaman: ['Shaman', 'Clairvoyant', 'Conjurer', 'Necromancer', 'Oracle'],
};

/** 技能图标 URL（/res 资产：image/sinimage/skill/{职业}/button/{文件}.bmp） */
export function skillIconUrl(classDir: string, iconFile: string): string {
  const seg = iconFile.split(' ').map(encodeURIComponent).join('%20');
  return `/res/image/sinimage/skill/${classDir}/button/${seg}`;
}