/**
 * 地图装饰模型清单（移植自 JPT2018 field.cpp AddStageObject）。
 * 路径为 ASE 相对路径，加载时转 field/小写/.smd。
 * mapId 已按 FieldMap 对齐（room/office 偏移修正）。
 */
export interface DecorEntry { path: string; bip: boolean }
export const MAP_DECOR: Record<number, DecorEntry[]> = {
  0: [
    { path: "forest\\\\3ani-01.ASE", bip: false },
    { path: "forest\\\\3ani-02.ASE", bip: false },
    { path: "forest\\\\3ani-03.ASE", bip: false },
    { path: "forest\\\\3ani-04.ASE", bip: false },
    { path: "forest\\\\3ani-05.ASE", bip: false },
    { path: "forest\\\\3ani-06.ASE", bip: false },
    { path: "forest\\\\3ani-07.ASE", bip: false },
    { path: "forest\\\\3ani-08.ASE", bip: false },
    { path: "forest\\\\3ani-09.ASE", bip: false },
    { path: "forest\\\\3ani-10.ASE", bip: false },
    { path: "forest\\\\3ani-11.ASE", bip: false },
    { path: "forest\\\\3ani-12.ASE", bip: false },
    { path: "forest\\\\3ani-13.ASE", bip: false },
    { path: "forest\\\\3ani-14.ASE", bip: false },
  ],
  1: [
    { path: "forest\\\\2ani-04.ASE", bip: false },
  ],
  3: [
    { path: "forest\\\\v_ani01.ASE", bip: false },
    { path: "forest\\\\v_ani02.ASE", bip: false },
    { path: "forest\\\\v_ani03.ASE", bip: false },
    { path: "forest\\\\v_ani04.ASE", bip: false },
    { path: "ricarten\\\\v-ani01.ASE", bip: false },
    { path: "ricarten\\\\v-ani02.ASE", bip: false },
    { path: "ricarten\\\\v-ani03.ASE", bip: false },
    { path: "ricarten\\\\v-ani04.ASE", bip: false },
    { path: "ricarten\\\\v-ani05.ASE", bip: false },
    { path: "ricarten\\\\v-ani06.ASE", bip: false },
    { path: "ricarten\\\\v-ani07.ASE", bip: false },
    { path: "ricarten\\\\v-ani08.ASE", bip: false },
    { path: "ricarten\\\\v-ani09.ASE", bip: false },
    { path: "ricarten\\\\v-ani10.ASE", bip: false },
    { path: "ricarten\\\\v-ani11.ASE", bip: false },
    { path: "ricarten\\\\v-ani12.ASE", bip: false },
    { path: "ricarten\\\\v-ani13.ASE", bip: false },
    { path: "ricarten\\\\v-ani14.ASE", bip: false },
    { path: "ricarten\\\\world_ani01.ASE", bip: false },
    { path: "ricarten\\\\world_ani02.ASE", bip: false },
    { path: "ricarten\\\\world_ani03.ASE", bip: false },
    { path: "ricarten\\\\world_ani04.ASE", bip: false },
    { path: "ricarten\\\\world_ani05.ASE", bip: false },
  ],
  6: [
    { path: "ruin\\\\ruin_ani01.ASE", bip: false },
  ],
  9: [
    { path: "forest\\\\v2-ani01.ASE", bip: false },
  ],
  12: [
    { path: "desert\\\\d4-ani01.ASE", bip: false },
  ],
  13: [
    { path: "dungeon\\\\dun-1-wheel.ase", bip: false },
  ],
  18: [
    { path: "forever-fall\\\\4ani-01.ASE", bip: false },
    { path: "forever-fall\\\\4ani-02.ASE", bip: false },
    { path: "forever-fall\\\\4ani-03.ASE", bip: false },
    { path: "forever-fall\\\\4ani-04.ASE", bip: false },
    { path: "forever-fall\\\\4ani-05.ASE", bip: false },
    { path: "forever-fall\\\\4ani-06.ASE", bip: false },
    { path: "forever-fall\\\\4ani-07.ASE", bip: false },
    { path: "forever-fall\\\\4ani-08.ASE", bip: false },
    { path: "forever-fall\\\\4ani-09.ASE", bip: false },
    { path: "forever-fall\\\\4ani-10.ASE", bip: false },
    { path: "forever-fall\\\\4ani-11.ASE", bip: false },
  ],
  19: [
    { path: "forever-fall\\\\3ani-01.ASE", bip: false },
    { path: "forever-fall\\\\3ani-02.ASE", bip: false },
    { path: "forever-fall\\\\3ani-03.ASE", bip: false },
    { path: "forever-fall\\\\3ani-04.ASE", bip: false },
    { path: "forever-fall\\\\3ani-05.ASE", bip: false },
    { path: "forever-fall\\\\3ani-06.ASE", bip: false },
    { path: "forever-fall\\\\3ani-07.ASE", bip: false },
  ],
  20: [
    { path: "forever-fall\\\\2ani-01.ASE", bip: false },
    { path: "forever-fall\\\\2ani-02.ASE", bip: false },
    { path: "forever-fall\\\\2ani-03.ASE", bip: false },
    { path: "forever-fall\\\\2ani-04.ASE", bip: false },
    { path: "forever-fall\\\\2ani-05.ASE", bip: false },
  ],
  21: [
    { path: "forever-fall\\\\1ani-01.ase", bip: false },
    { path: "forever-fall\\\\1ani-02.ase", bip: false },
    { path: "forever-fall\\\\1ani-03.ase", bip: false },
    { path: "forever-fall\\\\1ani-04.ase", bip: false },
    { path: "forever-fall\\\\1ani-05.ase", bip: false },
    { path: "forever-fall\\\\1ani-06.ase", bip: false },
    { path: "forever-fall\\\\1ani-07.ase", bip: false },
    { path: "forever-fall\\\\1ani-08.ase", bip: false },
    { path: "forever-fall\\\\1ani-09.ase", bip: false },
    { path: "forever-fall\\\\1ani-10.ase", bip: false },
    { path: "forever-fall\\\\1ani-11.ase", bip: false },
    { path: "forever-fall\\\\1ani-12.ase", bip: false },
    { path: "forever-fall\\\\1ani-13.ase", bip: false },
    { path: "forever-fall\\\\1ani-14.ase", bip: false },
    { path: "forever-fall\\\\1ani-15.ase", bip: false },
    { path: "forever-fall\\\\1ani-16.ase", bip: false },
    { path: "forever-fall\\\\1ani-17.ase", bip: false },
    { path: "forever-fall\\\\1ani-18.ase", bip: false },
    { path: "forever-fall\\\\1ani-19.ase", bip: false },
    { path: "forever-fall\\\\1ani-20.ase", bip: false },
    { path: "forever-fall\\\\1ani-21.ase", bip: false },
    { path: "forever-fall\\\\1ani-22.ase", bip: false },
    { path: "forever-fall\\\\1ani-23.ase", bip: false },
    { path: "forever-fall\\\\1ani-24.ase", bip: false },
    { path: "forever-fall\\\\1ani-25.ase", bip: false },
    { path: "forever-fall\\\\1ani-26.ase", bip: false },
    { path: "forever-fall\\\\1ani-27.ase", bip: false },
  ],
  22: [
    { path: "forever-fall\\\\piani-01.ase", bip: false },
    { path: "forever-fall\\\\piani-02.ase", bip: false },
    { path: "forever-fall\\\\piani-03.ase", bip: false },
    { path: "forever-fall\\\\piani-04.ase", bip: false },
    { path: "forever-fall\\\\piani-05.ase", bip: false },
    { path: "forever-fall\\\\piani-06.ase", bip: false },
    { path: "forever-fall\\\\piani-07.ase", bip: false },
    { path: "forever-fall\\\\piani-08.ase", bip: false },
    { path: "forever-fall\\\\piani-09.ase", bip: false },
    { path: "forever-fall\\\\piani-10.ase", bip: false },
    { path: "forever-fall\\\\piani-11.ase", bip: false },
    { path: "forever-fall\\\\piani-12.ase", bip: false },
    { path: "forever-fall\\\\piani-13.ase", bip: false },
    { path: "forever-fall\\\\piani-14.ase", bip: false },
    { path: "forever-fall\\\\piani-15.ase", bip: false },
    { path: "forever-fall\\\\piani-16.ase", bip: false },
    { path: "forever-fall\\\\piani-17.ase", bip: false },
    { path: "forever-fall\\\\piani-18.ase", bip: false },
    { path: "forever-fall\\\\piani-19.ase", bip: false },
    { path: "forever-fall\\\\piani-20.ase", bip: false },
    { path: "forever-fall\\\\piani-21.ase", bip: false },
    { path: "forever-fall\\\\piani-22.ase", bip: false },
    { path: "forever-fall\\\\piani-23.ase", bip: false },
    { path: "forever-fall\\\\piani-24.ase", bip: false },
    { path: "forever-fall\\\\piani-25.ase", bip: false },
    { path: "forever-fall\\\\piani-26.ase", bip: false },
    { path: "forever-fall\\\\piani-27.ase", bip: false },
    { path: "forever-fall\\\\piani-28.ase", bip: false },
    { path: "forever-fall\\\\piani-29.ase", bip: false },
    { path: "forever-fall\\\\piani-30.ase", bip: false },
    { path: "forever-fall\\\\piani-31.ase", bip: false },
    { path: "forever-fall\\\\piani-32.ase", bip: false },
    { path: "forever-fall\\\\piani-33.ase", bip: false },
    { path: "forever-fall\\\\piani-34.ase", bip: false },
    { path: "forever-fall\\\\piani-35.ase", bip: false },
    { path: "forever-fall\\\\piani-36.ase", bip: false },
    { path: "forever-fall\\\\piani-37.ase", bip: false },
    { path: "forever-fall\\\\piani-38.ase", bip: false },
    { path: "forever-fall\\\\piani-39.ase", bip: false },
    { path: "forever-fall\\\\piani-40.ase", bip: false },
    { path: "forever-fall\\\\piani-41.ase", bip: false },
    { path: "forever-fall\\\\piani-42.ase", bip: false },
    { path: "forever-fall\\\\piani-43.ase", bip: false },
    { path: "forever-fall\\\\ani_world01.ASE", bip: false },
    { path: "forever-fall\\\\ani_world02.ASE", bip: false },
    { path: "forever-fall\\\\ani_world03.ASE", bip: false },
    { path: "forever-fall\\\\ani_world04.ASE", bip: false },
    { path: "forever-fall\\\\ani_world05.ASE", bip: false },
    { path: "forever-fall\\\\ani_world06.ASE", bip: false },
  ],
  23: [
    { path: "dungeon\\\\dun-4-ani-01.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-02.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-03.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-06.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-07.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-08.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-09.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-14.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-15.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-16.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-17.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-18.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-19.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-20.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-21.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-22.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-23.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-24.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-25.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-26.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-27.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-28.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-29.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-30.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-31.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-32.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-33.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-34.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-35.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-36.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-37.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-01.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-02.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-03.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-04.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-05.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-06.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-07.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-08.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-09.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-10.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-11.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-12.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-13.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-14.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-15.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-16.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-17.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-18.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-19.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-20.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-21.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-22.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-23.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-24.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-25.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-26.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-27.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-28.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-29.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-30.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-31.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-32.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-33.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-34.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-35.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-36.ase", bip: false },
    { path: "dungeon\\\\dun-4-ani-37.ase", bip: false },
  ],
  24: [
    { path: "dungeon\\\\dun-5-ani-01.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-02.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-03.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-04.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-05.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-06.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-07.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-08.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-09.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-10.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-11.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-12.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-13.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-14.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-15.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-16.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-17.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-18.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-19.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-20.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-21.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-22.ASE", bip: false },
    { path: "dungeon\\\\dun-5-ani-01.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-02.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-03.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-04.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-05.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-06.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-07.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-08.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-09.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-10.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-11.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-12.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-13.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-14.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-15.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-16.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-17.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-18.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-19.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-20.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-21.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-22.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-23.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-24.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-25.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-26.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-27.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-28.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-29.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-30.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-31.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-32.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-33.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-34.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-35.ase", bip: false },
    { path: "dungeon\\\\dun-5-ani-36.ase", bip: false },
  ],
  25: [
    { path: "cave\\\\Tcave_ani01.ase", bip: false },
    { path: "cave\\\\Tcave_ani02.ase", bip: false },
    { path: "cave\\\\Tcave_ani03.ase", bip: false },
    { path: "cave\\\\Tcave_ani04.ase", bip: false },
    { path: "cave\\\\Tcave_ani05.ase", bip: false },
    { path: "cave\\\\Tcave_ani06.ase", bip: false },
    { path: "cave\\\\Tcave_ani07.ase", bip: false },
    { path: "cave\\\\Tcave_ani08.ase", bip: false },
    { path: "cave\\\\Tcave_ani09.ase", bip: false },
    { path: "cave\\\\Tcave_ani10.ase", bip: false },
    { path: "cave\\\\Tcave_ani11.ase", bip: false },
    { path: "cave\\\\Tcave_ani12.ase", bip: false },
    { path: "cave\\\\Tcave_ani13.ase", bip: false },
    { path: "cave\\\\Tcave_ani14.ase", bip: false },
    { path: "cave\\\\Tcave_ani15.ase", bip: false },
    { path: "cave\\\\Tcave_ani16.ase", bip: false },
  ],
  26: [
    { path: "cave\\\\Mcave_ani01.ASE", bip: false },
    { path: "cave\\\\Mcave_ani02.ASE", bip: false },
    { path: "cave\\\\Mcave_ani03.ASE", bip: false },
    { path: "cave\\\\Mcave_ani04.ASE", bip: false },
    { path: "cave\\\\Mcave_ani05.ASE", bip: false },
    { path: "cave\\\\Mcave_ani06.ASE", bip: false },
    { path: "cave\\\\Mcave_ani07.ASE", bip: false },
    { path: "cave\\\\Mcave_ani08.ASE", bip: false },
    { path: "cave\\\\Mcave_ani09.ASE", bip: false },
    { path: "cave\\\\Mcave_ani10.ASE", bip: false },
    { path: "cave\\\\Mcave_ani11.ASE", bip: false },
    { path: "cave\\\\Mcave_ani12.ASE", bip: false },
    { path: "cave\\\\Mcave_ani13.ASE", bip: false },
    { path: "cave\\\\Mcave_ani14.ASE", bip: false },
    { path: "cave\\\\Mcave_ani15.ASE", bip: false },
    { path: "cave\\\\Mcave_ani16.ASE", bip: false },
    { path: "cave\\\\Mcave_ani17.ASE", bip: false },
  ],
  27: [
    { path: "cave\\\\Dcave_ani01.ASE", bip: false },
    { path: "cave\\\\Dcave_ani02.ASE", bip: false },
    { path: "cave\\\\Dcave_ani03.ASE", bip: false },
    { path: "cave\\\\Dcave_ani04.ASE", bip: false },
    { path: "cave\\\\Dcave_ani05.ASE", bip: false },
    { path: "cave\\\\Dcave_ani06.ASE", bip: false },
    { path: "cave\\\\Dcave_ani07.ASE", bip: false },
    { path: "cave\\\\Dcave_ani08.ASE", bip: false },
    { path: "cave\\\\Dcave_ani09.ASE", bip: false },
    { path: "cave\\\\Dcave_ani10.ASE", bip: false },
    { path: "cave\\\\Dcave_ani11.ASE", bip: false },
    { path: "cave\\\\Dcave_ani12.ASE", bip: false },
    { path: "cave\\\\Dcave_ani13.ASE", bip: false },
    { path: "cave\\\\Dcave_ani14.ASE", bip: false },
  ],
  28: [
    { path: "iron\\\\i1-ani01_Bip.ASE", bip: true },
    { path: "iron\\\\i1-ani02_Bip.ASE", bip: true },
    { path: "iron\\\\i1-ani03_Bip.ASE", bip: true },
    { path: "iron\\\\i1-ani04_Bip.ASE", bip: true },
    { path: "iron\\\\i1-ani05_Bip.ASE", bip: true },
    { path: "iron\\\\i1-ani06_Bip.ASE", bip: true },
    { path: "iron\\\\i1-ani07_Bip.ASE", bip: true },
    { path: "iron\\\\i1-ani08_Bip.ASE", bip: true },
    { path: "iron\\\\i1-ani09_Bip.ASE", bip: true },
    { path: "iron\\\\i1-ani10_Bip.ASE", bip: true },
    { path: "iron\\\\i1-ani11_Bip.ASE", bip: true },
    { path: "iron\\\\iron-ani01.ASE", bip: false },
    { path: "iron\\\\iron-ani02.ASE", bip: false },
    { path: "iron\\\\iron-ani03.ASE", bip: false },
  ],
  29: [
    { path: "iron\\\\i2-bip01.ASE", bip: false },
    { path: "iron\\\\i2-bip02.ASE", bip: false },
    { path: "iron\\\\i2-bip03.ASE", bip: false },
    { path: "iron\\\\i2-bip04_ani.ASE", bip: true },
    { path: "iron\\\\i2-bip05_ani.ASE", bip: true },
    { path: "iron\\\\i2-bip06_ani.ASE", bip: true },
    { path: "iron\\\\i2-bip07_ani.ASE", bip: true },
    { path: "iron\\\\i2-bip08_ani.ASE", bip: true },
    { path: "iron\\\\i2-bip09.ASE", bip: false },
    { path: "iron\\\\i2-bip10.ASE", bip: false },
    { path: "iron\\\\i2-bip11_ani.ASE", bip: true },
    { path: "iron\\\\i2-bip12_ani.ASE", bip: true },
  ],
  30: [
    { path: "ice\\\\ice_ani_01.ASE", bip: false },
  ],
  31: [
    { path: "sod\\\\s-ani01_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani02_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani03_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani04_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani05_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani06_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani07_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani08_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani09_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani10_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani11_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani12_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani13_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani14_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani15_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani16_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani17_Bip.ASE", bip: true },
    { path: "sod\\\\s-ani18_Bip.ASE", bip: true },
  ],
  32: [
    { path: "ice\\\\ice_ani_01.ASE", bip: false },
    { path: "ice\\\\ice_bip_leewood01.ASE", bip: false },
    { path: "ice\\\\ice_bip_leewood03.ASE", bip: false },
    { path: "ice\\\\ice_bip_leewood04.ASE", bip: false },
    { path: "ice\\\\ice_bip_leaf01.ASE", bip: false },
    { path: "ice\\\\ice_bip_leaf02.ASE", bip: false },
    { path: "ice\\\\ice_bip_leaf03.ASE", bip: false },
    { path: "ice\\\\ice_bip_leaf04.ASE", bip: false },
    { path: "ice\\\\ice_bip_leaf05.ASE", bip: false },
    { path: "ice\\\\ice_bip_leaf06.ASE", bip: false },
    { path: "ice\\\\ice_bip_leaf07.ASE", bip: false },
  ],
  34: [
    { path: "castle\\\\wf_gate_ani.ASE", bip: false },
    { path: "castle\\\\crystal_ani01.ASE", bip: false },
    { path: "castle\\\\crystal_ani02.ASE", bip: false },
    { path: "castle\\\\crystal_ani03.ASE", bip: false },
    { path: "castle\\\\crystal_ani04.ASE", bip: false },
    { path: "castle\\\\crystal_ani05.ASE", bip: false },
    { path: "castle\\\\crystal_ani06.ASE", bip: false },
  ],
  35: [
    { path: "Greedy\\\\vane1_ani.ASE", bip: false },
    { path: "Greedy\\\\vane2_ani.ASE", bip: false },
    { path: "Greedy\\\\vane3_ani.ASE", bip: false },
    { path: "Greedy\\\\vane4_ani.ASE", bip: false },
    { path: "Greedy\\\\ani_tail.ASE", bip: false },
    { path: "Greedy\\\\ship_ani.ASE", bip: false },
    { path: "Greedy\\\\ship1_ani.ASE", bip: false },
    { path: "Greedy\\\\ship2_ani.ASE", bip: false },
    { path: "Greedy\\\\ship3_ani.ASE", bip: false },
    { path: "Greedy\\\\flower_animi01.ASE", bip: false },
    { path: "Greedy\\\\flower_animi02.ASE", bip: false },
    { path: "Greedy\\\\flower_animi03.ASE", bip: false },
    { path: "Greedy\\\\flower_animi04.ASE", bip: false },
    { path: "Greedy\\\\flower_animi05.ASE", bip: false },
    { path: "Greedy\\\\flower_animi06.ASE", bip: false },
    { path: "Greedy\\\\flower_animi07.ASE", bip: false },
    { path: "Greedy\\\\flower_animi08.ASE", bip: false },
    { path: "Greedy\\\\flower_animi09.ASE", bip: false },
    { path: "Greedy\\\\flower_animi10.ASE", bip: false },
    { path: "Greedy\\\\flower_ani00.ASE", bip: false },
    { path: "Greedy\\\\flower_ani01.ASE", bip: false },
    { path: "Greedy\\\\flower_ani02.ASE", bip: false },
    { path: "Greedy\\\\flower_ani03.ASE", bip: false },
    { path: "Greedy\\\\flower_ani04.ASE", bip: false },
    { path: "Greedy\\\\flower_ani05.ASE", bip: false },
    { path: "Greedy\\\\flower_ani06.ASE", bip: false },
    { path: "Greedy\\\\flower_ani07.ASE", bip: false },
    { path: "Greedy\\\\flower_ani08.ASE", bip: false },
    { path: "Greedy\\\\flower_ani09.ASE", bip: false },
    { path: "Greedy\\\\door.ASE", bip: false },
  ],
  38: [
    { path: "lost\\\\wf_ani.ASE", bip: false },
    { path: "lost\\\\ani_shop01.ASE", bip: false },
    { path: "lost\\\\ani_shop02.ASE", bip: false },
    { path: "lost\\\\ani_shop03.ASE", bip: false },
    { path: "lost\\\\ani_shop04.ASE", bip: false },
  ],
  43: [
    { path: "dungeon\\\\Dun-6a-ani-001.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-002.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-003.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-004.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-005.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-006.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-007.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-008.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-009.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-010.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-011.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-012.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-013.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-014.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-015.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-016.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-017.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-018.ASE", bip: false },
    { path: "dungeon\\\\Dun-6a-ani-019.ASE", bip: false },
  ],
};

export function mapDecorList(mapId: number): DecorEntry[] { return MAP_DECOR[mapId] || []; }
